title: "Linear Algebra, Geometry, and Computation"
author: "Mark Crovella"
logo: images/DiagramAR-icon.png
only_build_toc_files: true
copyright: '2020-2021'
repository:
        url: https://github.com/mcrovella/CS132-Geometric-Algorithms
html:
        favicon: images/DiagramAR-icon.png
        use_repository_button: true
execute:
  execute_notebooks: "auto"
